### PR TITLE
Use conventional Go style for exported variables

### PR DESCRIPTION
**Pull request by bwhaley**

### CODE REVIEW

**Comment by yorinasub17** [comment]
Looks like there is a build error:
```
# github.com/gruntwork-io/go-commons/version
version/version.go:16:6: Version redeclared in this block
	previous declaration at version/version.go:12:2
version/version.go:17:2: cannot use Version (type func() string) as type string in return argument
```

**Comment by bwhaley** [comment]
Oh, duh. 🤦‍♂️

Any objection to renaming this function to `GetVersion()`?

**Review by yorinasub17 — APPROVED** [review]
LGTM! This is backward incompatible, but AFAIK it only affects `repo-copier`. I can open a PR there once this is merged and released!

**Comment by bwhaley** [comment]
Thanks for the reviews and for being patient with my neurotic Go syntax obsession.

**Comment by bwhaley** [comment]
https://github.com/gruntwork-io/go-commons/releases/tag/v0.9.0

**Pull request merged**
