### PR TITLE
Port retry package from kubergrunt

### PR DESCRIPTION
**Pull request by yorinasub17**
This DRYs the `retry` package from `kubergrunt` so that it can be reused across CLIs (e.g., most recent use case is `cloud-nuke`: https://github.com/gruntwork-io/cloud-nuke/pull/183)

### CODE REVIEW

**Review by brikis98 — COMMENTED** [review]
Wouldn't the retry logic from Terratest be the better one to port? https://github.com/gruntwork-io/terratest/blob/master/modules/retry/retry.go

**Comment by yorinasub17** [comment]
These are exactly the same as the terratest functions (the `E` flavors). I only ported the things that we need to avoid adding and maintaining code we don't use.

**Comment by brikis98** [comment]
Hm, wouldn't that be more confusing? That is, if we port all the retry functions, then we can remove them from all the other places right away. Whereas if we port only a few, then when someone goes to update the other locations, some items will be missing, and it won't be obvious if that's intentional or not, or if there are other differences, and we might never migrate over...

**Comment by yorinasub17** [comment]
> That is, if we port all the retry functions, then we can remove them from all the other places right away.

This is where I am confused. AFAIK we don't have these functions outside of `kubergrunt` (which was why it was copied over there), and I decided to move the kubergrunt functions here because of https://github.com/gruntwork-io/cloud-nuke/pull/183.

**Comment by yorinasub17** [comment]
By the way, the reason I am pushing back on this is that it is some amount of non-zero effort to port the functions over from terratest, since we have to sanitize the logging and the `t` object. Vs copying over from `kubergrunt`, which already sanitized these, is much easier.

I don't quite have the time or effort to do more than what's here before I am off and I didn't want to block the `cloud-nuke` PR, which was why I did the minimal effort here.

Just wanted to provide the context. Happy to keep this PR open until we've sanitized and ported all the functions from terratest if you feel strongly, just that that might make this PR linger.

**Review by brikis98 — APPROVED** [review]
Thx for the context. I don't think my objection here is important enough to block this. At some point, it would be great to have all our Go code—Terragrunt, Terratest, cloud-nuke—use the same retry logic from `go-commons`, but it's not urgent, and not _that_ hard to do later. And even if we don't make it all DRY, this isn't logic so complicated or updated so often that I'm worried about major bugs as a result. So merge away!

**Comment by yorinasub17** [comment]
Thanks for review and sharing the concerns and sanity check! Going to merge and release this now.

**Pull request merged**
